version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: ifugao-bmi-backend
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=bmi_monitor.settings
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:8000/api
    container_name: ifugao-bmi-frontend
    ports:
      - '5173:80'
    depends_on:
      - backend
